version: "3.8"

services:
  db:
    image: postgres:13
    container_name: chatapp-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: chatapp-backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/chatapp
      PORT: 4000
    ports:
      - "4000:4000"

volumes:
  postgres_data:
